test:
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  sandbox: true

development:
  consumer_key:  <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  sandbox: false

production:
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  sandbox: false