test:
  consumer_key: "julianorinyol"
  consumer_secret: "035478b9892a814e"
  sandbox: true

development:
  consumer_key: "julianorinyol"
  consumer_secret: "035478b9892a814e"
  sandbox: false

production:
  consumer_key: "julianorinyol"
  consumer_secret: "035478b9892a814e"
  sandbox: false